### ISSUE TITLE
RwLock unneeded

### ISSUE THREAD

**Issue by mike-kfed** [zupzup/rust-jwt-example#1]
Hi, I read your article on the logrocket blog, very helpful information, thanks!

I noticed though that you use RwLock, but you never write lock. Therefore you can make the access to your read-only db lock-free only using `Arc`. This should make the endpoint better performing and the code shorter.

Also it is suggested to use `tokio::sync::RwLock` in async code as it will fairly queue the r/w-locks across tasks on all OS kernels. Especially `std::sync::RwLock` on Linux kernel will likely starve writers when there is a read-heavy workload. So if you want to keep the locking-example, you should consider switching to a fairer locking implementation.

**Comment by zupzup** [comment]
You're right! I think I had the initialization outside of the `users` creation at first, but as it stands, it's not needed, you're 100% correct.

Thanks for the suggestion regarding the `tokio` RwLock - I was under the impression, that the tokio locks should only be used, if they are needed beyond an await point, as described [here](https://docs.rs/tokio/1.2.0/tokio/sync/struct.Mutex.html), but I guess that's only true for the Mutex and not for RwLock.

I changed it in the example, thanks for the heads up :+1:
